print("Magicpin Food Delivery Details".center(50,"*"))

booking_id = input("enter the Booking id:")
item_name = input("enter the Item Name:")
item_price = float(input("enter the Item Price:"))
discount_price = float(input("enter the Discount Value:"))
delivery_distance = input("Enter the Distance:")
delivery_charges = int(input("Enter the Delivery Charges:"))
total_price = (item_price - discount_price + delivery_charges)
print("Total Price : {}%".format(total_price))
delivery_person_name = input("Enter the delivery person name:")
delivery_contact_details = int(input("Enter the contact number:"))
delivery_location = input("Enter the Delivery Location:")
